### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by slaFFik** [10up/phpfpm-image#3]
Could you please add support for PHP 7.2?

**Comment by Viper007Bond** [comment]
An upstream update is needed: https://github.com/johnpbloch/phpfpm-images/pull/1

Meanwhile you can modify your `docker-compose.yml` to use `image: viper007bond/phpfpm` instead which will use PHP 7.2.

https://github.com/10up/phpfpm-image/compare/master...Viper007Bond:master
